[tool.poetry]
name = "ni6738-analog-card-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "ni6738_analog_card"}]

[tool.poetry.dependencies]
python = "^3.11"

pydantic = "^1.10.4"

units = {path = "../../../common/units", develop = true}
device-config = {path = "../../device/device.configuration", develop = true}
sequencer-configuration = {path = "../../sequencer/sequencer.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
