[tool.poetry]
name = "atom-detector-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "atom_detector"}]

[tool.poetry.dependencies]
python = "^3.11"

device-configuration-editor = {path = "../../device/device.configuration_editor", develop = true}
atom-detector-configuration = {path = "../atom_detector.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
