[tool.poetry]
name = "atom-detector-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "atom_detector"}]

[tool.poetry.dependencies]
python = "^3.11"
pyqt6 = "^6.5.0"

device-configuration-editor = {path = "../../device/device.configuration_editor", develop = true}
atom-detector-configuration = {path = "../atom_detector.configuration", develop = true}
device-server-name = {path = "../../remote_device/device_server/device_server.name", develop = true}


[tool.poetry.group.test.dependencies]
settings-model = {path = "../../../common/settings_model", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
