[tool.poetry]
name = "trap-signal-generator-configuration"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "trap_signal_generator"}]

[tool.poetry.dependencies]
python = "^3.10"
settings-model = {path = "../../../../common/settings_model", develop = true}
pydantic = "^1.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
