[tool.poetry]
name = "analog-lane-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "analog_lane"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

expression = {path = "../../../../common/expression", develop = true}
settings-model = {path = "../../../../common/settings_model", develop = true}
units = {path = "../../../../common/units", develop = true}
lane-configuration = {path = "../../../../common/lane/lane.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
