[tool.poetry]
name = "core-compilation"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11"

numpy = "^1.26.3"
python-benedict = "^0.33.1"

core-device = {path = "../core.device", develop = true}
core-session = {path = "../core.session", develop = true}


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
