[tool.poetry]
name = "spincore-pulse-blaster-configuration-editor"
version = "1.0.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "spincore_pulse_blaster"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

pyside6 = "^6.6.1"

spincore-pulse-blaster-configuration = {path = "../spincore_pulse_blaster.configuration/", develop = true}
caqtus-device = {path = "../../../../../caqtus.device/", develop = true}
caqtus-types = {path = "../../../../../caqtus.types/", develop = true}
caqtus-gui-condetrol = {path = "../../../../../caqtus.gui/caqtus.gui.condetrol/", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
