[tool.poetry]
name = "experiment-control-sequence-runner"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "experiment_control"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

numpy = "^1.24.3"
pyqt6 = "^6.5.0"

util = {path = "../../util", develop = true}
camera-runtime = {path = "../../devices/cameras/camera/camera.runtime", develop = true}
device-config = {path = "../../devices/device/device.configuration", develop = true}
device-runtime = {path = "../../devices/device/device.runtime", develop = true}
experiment-configuration = {path = "../../common/experiment/experiment.configuration", develop = true}
experiment-session = {path = "../../common/experiment/experiment.session", develop = true}
remote-device-client = {path = "../../devices/remote_device/remote_device_client", develop = true}
sequence-configuration = {path = "../../common/sequence/sequence.configuration", develop = true}
sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}
units = {path = "../../common/units", develop = true}
variable-name = {path = "../../common/variable/variable.name", develop = true}
variable-namespace = {path = "../../common/variable/variable.namespace", develop = true}
experiment-control-compute-device-parameters = {path = "../experiment_control.compute_device_parameters", develop = true}
data-types = {path = "../../common/types/data_types", develop = true}
parameter-types = {path = "../../common/types/parameter_types", develop = true}
sequencer-runtime = {path = "../../devices/sequencer/sequencer.runtime", develop = true}
tweezer-arranger-runtime = {path = "../../devices/tweezer_arranger/tweezer_arranger.runtime", develop = true}


[tool.poetry.group.dev.dependencies]
sphinx = "^7.2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
