[tool.poetry]
name = "swabian-pulse-streamer-runtime"
version = "1.0.1"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "swabian_pulse_streamer"}]

[tool.poetry.dependencies]
python = "^3.11"

attrs = "^23.1.0"
pulsestreamer = "^1.7.0"

caqtus-device = {path = "../../../../../caqtus.device/", develop = true}


[tool.poetry.plugins."experiment_control.devices"]
"SwabianPulseStreamer" = "swabian_pulse_streamer.runtime:SwabianPulseStreamer"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.4.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
matplotlib = "^3.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
