[tool.poetry]
name = "viewer-single-shot-viewers"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "viewer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

pyqt6 = "^6.5.1"

matplotlib = "^3.7.1"
numpy = "^1.24.3"

analyza-loading-importers = {path = "../../analyza/analyza.loading/analyza.loading.importers", develop = true}
experiment-session = {path = "../../common/experiment/experiment.session", develop = true}
image-types = {path = "../../common/types/image_types", develop = true}
sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}
qabc = {path = "../../common/widgets/qabc", develop = true}
parameter-types = {path = "../../common/types/parameter_types", develop = true}
sequence-hierarchy = {path = "../../common/widgets/sequence_hierarchy", develop = true}
viewer-sequence-watcher = {path = "../viewer.sequence_watcher", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
