[tool.poetry]
name = "viewer-single-shot-viewers"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "viewer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

pyqt6 = "^6.5.1"

sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
