[tool.poetry]
name = "spectum-awg-m4i66xx-x8-configuration"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "spectum_awg_m4i66xx_x8"}]

[tool.poetry.dependencies]
python = "^3.10"

pydantic = "^1.10.4"

device-config = {path = "../../device/device.configuration", develop = true}
settings-model = {path = "../../../common/settings_model", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
