# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details


version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - graphviz
  jobs:
    # We need to use uv to resolve the dependencies.
    # Would be better to execute arbitrary commands to have uv build to docs, but
    # in this mode, we can't use apt_packages to install graphviz.
    # See: https://github.com/readthedocs/readthedocs.org/issues/9599
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group dev --link-mode=copy
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv pip freeze

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true
