# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details


version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
     # Install poetry in the virtualenv created by RTD
     - python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
     - pip install poetry
     # Install the project dependencies and build the documentation in the virtualenv
     # created by poetry
     - poetry install --with doc
     - poetry run python -m sphinx doc/source $READTHEDOCS_OUTPUT/html/ --fail-on-warning --keep-going
