[tool.poetry]
name = "caqtus"
version = "1.0.14"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

utils = {path = "lib/utils", develop = true}
types = {path = "lib/types/", develop = true}
device = {path = "lib/device/", develop = true}
session = {path = "lib/session/", develop = true}
analysis = {path = "lib/analysis/", develop = true}
shot-compilation = {path = "lib/shot_compilation/", develop = true}
experiment-control = {path = "lib/experiment_control/", develop = true}

gui-condetrol = {path = "lib/caqtus.gui/gui.condetrol/", develop = true}
gui-graphplot = {path = "lib/caqtus.gui/gui.graphplot/", develop = true}
gui-shotviewer = {path = "lib/caqtus.gui/gui.shotviewer/", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
mypy = "^1.9.0"
pyright = "^1.1.355"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
