[tool.poetry]
name = "caqtus"
version = "1.0.13"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

caqtus-utils = {path = "caqtus/caqtus.utils", develop = true}
caqtus-types = {path = "caqtus/caqtus.types/", develop = true}
caqtus-device = {path = "caqtus/caqtus.device/", develop = true}
caqtus-session = {path = "caqtus/caqtus.session/", develop = true}
caqtus-analysis = {path = "caqtus/caqtus.analysis/", develop = true}
caqtus-shot-compilation = {path = "caqtus/caqtus.shot_compilation/", develop = true}
caqtus-experiment-control = {path = "caqtus/caqtus.experiment_control/", develop = true}

caqtus-gui-condetrol = {path = "caqtus/caqtus.gui/caqtus.gui.condetrol/", develop = true}
caqtus-gui-graphplot = {path = "caqtus/caqtus.gui/caqtus.gui.graphplot/", develop = true}
caqtus-gui-shotviewer = {path = "caqtus/caqtus.gui/caqtus.gui.shotviewer/", develop = true}

caqtus-device-library-swabian-pulse-streamer = {path = "caqtus/caqtus.device_library/caqtus.device_library.swabian_pulse_streamer", optional = true, develop = true}

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
mypy = "^1.9.0"
pyright = "^1.1.355"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
