[tool.poetry]
name = "caqtus"
version = "1.0.13"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

caqtus-utils = {path = "caqtus.utils"}
caqtus-types = {path = "caqtus.types/"}
caqtus-device = {path = "caqtus.device/"}
caqtus-session = {path = "caqtus.session/"}
caqtus-analysis = {path = "caqtus.analysis/"}
caqtus-shot-compilation = {path = "caqtus.shot_compilation/"}
caqtus-experiment-control = {path = "caqtus.experiment_control/"}

caqtus-gui-condetrol = {path = "caqtus.gui/caqtus.gui.condetrol/"}
caqtus-gui-graphplot = {path = "caqtus.gui/caqtus.gui.graphplot/"}
caqtus-gui-shotviewer = {path = "caqtus.gui/caqtus.gui.shotviewer/"}

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
mypy = "^1.9.0"
pyright = "^1.1.355"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
