[tool.poetry]
name = "siglent-sdg6000x"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "siglent_sdg6000x"}]

[tool.poetry.dependencies]
python = "^3.10"
pyvisa = "^1.12.0"
pydantic = "^1.10.2"
device = { path = "../device/", develop = true }
settings_model = { path = "../../common/settings_model/", develop = true }


[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
