[tool.poetry]
name = "sequencer-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "sequencer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
pyqt6 = "^6.5.1"
sequencer-configuration = {path = "../sequencer.configuration", develop = true}


[tool.poetry.group.test.dependencies]
experiment-configuration = {path = "../../../common/experiment/experiment.configuration", develop = true}
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
