[tool.poetry]
name = "orca-quest"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "orca_quest"}]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
pydantic = "^1.10.2"
device = { path = "../../device/", develop = true }
camera = { path = "../camera/", develop = true }


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
matplotlib = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
