[tool.poetry]
name = "siglent-sdg6000x-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "siglent_sdg6000x"}]

[tool.poetry.dependencies]
python = "^3.10"
device-config = {path = "../../../common/device_config", develop = true}
settings-model = {path = "../../../common/settings_model", develop = true}
sequence = {path = "../../../common/sequence", develop = true}
units = {path = "../../../common/units", develop = true}
expression = {path = "../../../common/expression", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
