[tool.poetry]
name = "single-atom-detector"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "single_atom_detector"}]

[tool.poetry.dependencies]
python = "^3.11"

numpy = "^1.24.3"
pyyaml = "^6.0"

roi = {path = "../../../common/roi", develop = true}
settings-model = {path = "../../../common/settings_model", develop = true}
util = {path = "../../../util", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
