[tool.poetry]
name = "orca-quest-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "orca_quest"}]

[tool.poetry.dependencies]
python = "^3.11"

util = {path = "../../../../util", develop = true}
camera-configuration = {path = "../../camera/camera.configuration", develop = true}
device-config = {path = "../../../device/device.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
