[tool.poetry]
name = "sequence-hierarchy"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "sequence_hierarchy"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"
pyqt6 = "^6.5.1"
anytree = "^2.8.0"

concurrent-updater = {path = "../../concurrent_updater", develop = true}
experiment-session = {path = "../../experiment/experiment.session", develop = true}
sequence-configuration = {path = "../../sequence/sequence.configuration", develop = true}
sequence-runtime = {path = "../../sequence/sequence.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
