[tool.poetry]
name = "device-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "device"}]

[tool.poetry.dependencies]
python = "^3.10"


attrs = "^23.1.0"

util = {path = "../../../util", develop = true}
device-name = {path = "../device.name", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
