[tool.poetry]
name = "swabian-pulse-streamer-configuration-editor"
version = "1.0.2"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "swabian_pulse_streamer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

pyside6 = "^6.6.1"

swabian-pulse-streamer-configuration = {path = "../swabian_pulse_streamer.configuration/"}
caqtus-device = {path = "../../../../../caqtus.device/"}
caqtus-types = {path = "../../../../../caqtus.types/"}
caqtus-gui-condetrol = {path = "../../../../../caqtus.gui/caqtus.gui.condetrol/"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
