[tool.poetry]
name = "visual-sequence-watcher"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "visual"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^1.5.3"
pyqt6 = "^6.4.2"
pyqt6-charts = "^6.4.0"
experiment-session = {path = "../../common/experiment/experiment.session", develop = true}
sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
