[tool.poetry]
name = "visual-sequence-watcher"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "visual"}]

[tool.poetry.dependencies]
python = "^3.8,<3.12"
pandas = "^1.5.3"
experiment-session = {path = "../../common/experiment/experiment.session", develop = true}
sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}
concurrent-updater = {path = "../../common/concurrent_updater", develop = true}
matplotlib = "^3.7.1"
seaborn = "^0.12.2"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
