[tool.poetry]
name = "homogenize"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.12"
matplotlib = "^3.7.1"
spectum-awg-m4i66xx-x8-runtime = {path = "../../spectum_awg_m4i66xx-x8/spectum_awg_m4i66xx-x8.runtime", develop = true}
opencv-python = "^4.7.0.72"
trap-signal-generator-runtime = {path = "../trap_signal_generator/trap_signal_generator.runtime", develop = true}
numpy = "^1.24.2"
pixelfly = {path = "../pixelfly", develop = true}
trap-signal-generator-configuration = {path = "../trap_signal_generator/trap_signal_generator.configuration", develop = true}
jupyter = "^1.0.0"
analyze-spots = {path = "../analyze_spots", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
