[tool.poetry]
name = "homogenize"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pixelfly = {path = "../pixelfly", develop = true}
numpy = "^1.24.2"
matplotlib = "^3.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
