[tool.poetry]
name = "aod-tweezer-arranger-utilities"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{ include = "aod_tweezer_arranger" }]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

numpy = "^1.25.1"
scipy = "^1.11.1"
pydantic = "^1.0"
jupyter = "^1.0.0"
matplotlib = "^3.7.2"

aod-tweezer-arranger-configuration = { path = "../aod_tweezer_arranger.configuration", develop = true }
experiment-session = { path = "../../../common/experiment/experiment.session", develop = true }
device-name = { path = "../../device/device.name", develop = true }
spectum-awg-m4i66xx-x8-runtime = { path = "../../spectum_awg_m4i66xx-x8/spectum_awg_m4i66xx-x8.runtime", develop = true }
aod-tweezer-arranger-runtime = { path = "../aod_tweezer_arranger.runtime", develop = true }
pixelfly-runtime = { path = "../../cameras/pixelfly/pixelfly.runtime", develop = true }
analyze-spots = { path = "../../tweezers/analyze_spots", develop = true }


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
