[tool.poetry]
name = "swabian-pulse-streamer-configuration"
version = "1.0.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "swabian_pulse_streamer"}]

[tool.poetry.dependencies]
python = "^3.11"

caqtus-device = {path = "../../../../../caqtus.device"}
caqtus-utils = {path = "../../../../../caqtus.utils"}




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
