[tool.poetry]
name = "remote-device-server"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "remote_device_server"}]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
pydantic = "^1.10.2"
cdevice = { path = "../cdevice/", develop = true }
orca_quest = {path = "../cameras/orca_quest/", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
