[tool.poetry]
name = "core-device"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11"

numpy = "^1.26.2"

util = {path = "../../util", develop = true}
core-types = {path = "../core.types", develop = true}
pydantic = "^2.5.3"


[tool.poetry.group.dev.dependencies]
sphinx = "^7.2.6"
jupyter = "^1.0.0"
black = "^23.12.1"
matplotlib = "^3.8.2"
nbsphinx = "^0.9.3"
ipympl = "^0.9.3"
jupyterlab-code-formatter = "^2.2.1"
isort = "^5.13.2"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
hypothesis = "^6.92.1"
sympy = "^1.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
