[tool.poetry]
name = "sequence-hierarchy"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "sequence_hierarchy"}]

[tool.poetry.dependencies]
python = "^3.11"

pyqt6 = "^6.5.1"
anytree = "^2.8.0"

core-session = {path = "../../../core/core.session", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
