[tool.poetry]
name = "imaging-source-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "imaging_source"}]

[tool.poetry.dependencies]
python = "^3.11"
attrs = "^23.2.0"
core-device = {path = "../../../../core/core.device", develop = true}
util = {path = "../../../../util", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
