[tool.poetry]
name = "orca-quest-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "orca_quest"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.1"
pydantic = "^1.10.4"
camera-runtime = {path = "../../camera/camera.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
