[tool.poetry]
name = "elliptec-ell14-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "elliptec_ell14"}]

[tool.poetry.dependencies]
python = "^3.12"

pyqt6 = "^6.5.1"

condetrol = {path = "../../../ui/condetrol", develop = true}
elliptec-ell14-configuration = {path = "../elliptec_ell14.configuration", develop = true}
serial-port-widget = {path = "../../../ui/widgets/serial_port_widget", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
