[tool.poetry]
name = "elliptec-ell14-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "elliptec_ell14"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

pyqt6 = "^6.5.1"

device-configuration-editor = {path = "../../device/device.configuration_editor", develop = true}
elliptec-ell14-configuration = {path = "../elliptec_ell14.configuration", develop = true}
device-server-name = {path = "../../remote_device/device_server/device_server.name", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
