[tool.poetry]
name = "swabian-pulse-streamer-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "swabian_pulse_streamer"}]

[tool.poetry.dependencies]
python = "^3.11"

util = {path = "../../../util", develop = true}
core-device = {path = "../../../core/core.device", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
