[tool.poetry]
name = "atom-detector-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "atom_detector"}]

[tool.poetry.dependencies]
python = "^3.11"

attrs = "^23.1.0"

atom-detector-configuration = {path = "../atom_detector.configuration", develop = true}
device-runtime = {path = "../../device/device.runtime", develop = true}
single-atom-detector = {path = "../single_atom_detector", develop = true}

[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
