[tool.poetry]
name = "sequencer-runtime"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "sequencer"}]

[tool.poetry.dependencies]
python = "^3.11"
sequencer-instructions = {path = "../sequencer.instructions", develop = true}
device-runtime = {path = "../../device/device.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
