[tool.poetry]
name = "parse-optimization"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "parse_optimization"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
sequence-runtime = {path = "../sequence/sequence.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
