[tool.poetry]
name = "caqtus-device"
version = "1.0.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "caqtus"}]

[tool.poetry.dependencies]
python = "^3.11"

numpy = "^1.26.4"
sympy = "^1.12"
tblib = "^3.0.0"
pydantic = "^2.6.4"

caqtus-utils = {path = "../caqtus.utils"}
caqtus-types = {path = "../caqtus.types"}


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
hypothesis = "^6.99.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
