[tool.poetry]
name = "atom-detector-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "atom_detector"}]

[tool.poetry.dependencies]
python = "^3.11"

device-config = {path = "../../device/device.configuration", develop = true}
single-atom-detector = {path = "../single_atom_detector", develop = true}
validate-arguments = {path = "../../../common/validate_arguments"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
