[tool.poetry]
name = "camera"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
pydantic = "^1.10.2"
device = { path = "../../device/", develop = true }
settings_model = { path = "../../../common/settings_model/", develop = true }
numpy = "^1.23.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
