[tool.poetry]
name = "ni6738-analog-card"
version = "0.4.0"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

nidaqmx = "^0"

caqtus = {git = "https://github.com/damienBloch/caqtus.git", branch="refactor_shot_compilation"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
