[tool.poetry]
name = "parameter-types"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "parameter_types"}]

[tool.poetry.dependencies]
python = "^3.11"
units = {path = "../../units", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
