[tool.poetry]
name = "mapping-model"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "mapping_model"}]

[tool.poetry.dependencies]
python = "^3.11"
pyqt6 = "^6.5.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
