[tool.poetry]
name = "remote-device-client"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "remote_device_client"}]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
cdevice = { path = "../../cdevice/", develop = true }
orca_quest = {path = "../../cameras/orca_quest/", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
