[tool.poetry]
name = "roi"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

numpy = "^1.24.2"

util = {path = "../../util", develop = true}

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
