[tool.poetry]
name = "condetrol"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique.fr>"]

[tool.poetry.dependencies]
python = "^3.10"
PyQt5 = "^5.15.7"
QDarkStyle = "^3.1"
appdirs = "^1.4.4"
settings_model = { path = "../common/settings_model/", develop = true }
experiment_config = { path = "../common/experiment_config/", develop = true }
experiment_manager = { path = "../common/experiment_manager/", develop = true }
sequence = { path = "../common/sequence/", develop = true }
Send2Trash = "^1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.6.0"
jupyter = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
