[tool.poetry]
name = "core-types"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11"

pint = "^0.23"
numpy = "^1.26.2"
token-utils = "^0.1.8"

util = {path = "../../util", develop = true}



[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
