[tool.poetry]
name = "expression-widget"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "expression_widget"}]

[tool.poetry.dependencies]
python = "^3.8, <3.12"
pyqt6 = "^6.5.0"
expression = {path = "../../expression", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
