[tool.poetry]
name = "caqtus-device-library-ni6738-analog-card"
version = "1.0.0"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"
packages = [{include = "caqtus"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

nidaqmx = "^0.6.5"
numpy = "^1.24.1"
attrs = "^23.1.0"
pyside6 = "^6.6.2"

caqtus-device = {path = "../../caqtus.device", develop = true}
caqtus-utils = {path = "../../caqtus.utils", develop = true}
caqtus-types = {path = "../../caqtus.types", develop = true}
caqtus-gui-condetrol = {path = "../../caqtus.gui/caqtus.gui.condetrol", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
