[tool.poetry]
name = "analyze-spots"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "analyze_spots"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.24.2"
opencv-python = "^4.7.0.72"
roi = {path = "../../../common/roi", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
