[tool.poetry]
name = "atom-detector"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "atom_detector"}]

[tool.poetry.dependencies]
python = "^3.11"
settings-model = {path = "../../../common/settings_model", develop = true}
numpy = "^1.24.2"
roi = {path = "../../../common/roi", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
