[tool.poetry]
name = "variable-namespace"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "variable"}]

[tool.poetry.dependencies]
python = "^3.10"
variable-name = {path = "../variable.name", develop = true}
python-benedict = "^0.30.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
