[tool.poetry]
name = "siglent-sdg6000x-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "siglent_sdg6000x"}]

[tool.poetry.dependencies]
python = "^3.10"
pyvisa = "^1.13.0"
device = {path = "../../device", develop = true}
settings-model = {path = "../../../common/settings_model", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
