[tool.poetry]
name = "siglent-sdg6000x-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "siglent_sdg6000x"}]

[tool.poetry.dependencies]
python = "^3.10"
pyvisa = "^1.13.0"

device-runtime = {path = "../../device/device.runtime", develop = true}
settings-model = {path = "../../../common/settings_model", develop = true}


[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"


[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
mypy = "^1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
