[tool.poetry]
name = "lane-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "lane"}]

[tool.poetry.dependencies]
python = "^3.11"

pydantic = "^1.0"

settings-model = {path = "../../settings_model", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
