[tool.poetry]
name = "core-control"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

numpy = "^1.26.2"

util = {path = "../../util", develop = true}
core-configuration = {path = "../core.configuration", develop = true}
core-types = {path = "../core.types", develop = true}
core-device = {path = "../core.device", develop = true}
core-session = {path = "../core.session", develop = true}
sequencer-channel = {path = "../../devices/sequencer/sequencer.channel", develop = true}
sequencer-configuration = {path = "../../devices/sequencer/sequencer.configuration", develop = true}
sequencer-instructions = {path = "../../devices/sequencer/sequencer.instructions", develop = true}
spincore-sequencer-configuration = {path = "../../devices/spincore_sequencer/spincore_sequencer.configuration", develop = true}
ni6738-analog-card-configuration = {path = "../../devices/ni6738_analog_card/ni6738_analog_card.configuration", develop = true}
elliptec-ell14-configuration = {path = "../../devices/elliptec_ell14/elliptec_ell14.configuration", develop = true}
swabian-pulse-streamer-configuration = {path = "../../devices/swabian_pulse_streamer/swabian_pulse_streamer.configuration", develop = true}
tweezer-arranger-configuration = {path = "../../devices/tweezer_arranger/tweezer_arranger.configuration", develop = true}
python-benedict = "^0.33.0"


[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
mypy = "^1.7.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
