[tool.poetry]
name = "sequencer-instructions"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "sequencer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

sequencer-channel = {path = "../sequencer.channel", develop = true}


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
black = "^23.3.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
numpy = "^1.26.0"
hypothesis = "^6.86.2"
sympy = "^1.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
