[tool.poetry]
name = "elliptec-ell14-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "elliptec_ell14"}]

[tool.poetry.dependencies]
python = "^3.10"
thorlabs-elliptec = "^1.1.0"
device = {path = "../../device", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
