[tool.poetry]
name = "channel-output-editor"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"
pyside6 = "^6.6.1"
qdarkstyle = "^3.2.3"
matplotlib = "^3.8.2"
core-device = {path = "../../../core/core.device", develop = true}
qabc = {path = "../qabc", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^24.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
