[tool.poetry]
name = "orca-quest-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "orca_quest"}]

[tool.poetry.dependencies]
python = "^3.11"

device-configuration-editor = {path = "../../../device/device.configuration_editor", develop = true}
device-server-name = {path = "../../../remote_device/device_server/device_server.name", develop = true}
orca-quest-configuration = {path = "../orca_quest.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
