[tool.poetry]
name = "orca-quest-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "orca_quest"}]

[tool.poetry.dependencies]
python = "^3.12"

util = {path = "../../../../util", develop = true}
orca-quest-configuration = {path = "../orca_quest.configuration", develop = true}
condetrol = {path = "../../../../ui/condetrol", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
