[project]
name = "caqtus-parsing"
version = "0.2.0"
description = "Contains code to parse expression for caqtus-suite package."
authors = [
    { name = "light-scattering-io", email = "lecaqtus66@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
caqtus-parsing = "caqtus_parsing:main"

[tool.maturin]
module-name = "caqtus_parsing._core"
python-packages = ["caqtus_parsing"]
python-source = "src"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "Cargo.toml" },
    { file = "**/*.rs" },
    { file = "../caqtus-parsing-rs/Cargo.toml" },
    { file = "../caqtus-parsing-rs/**/*.rs" },
]
# Uncomment to build rust code in development mode
# config-settings = { build-args = '--profile=dev' }

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "pyright>=1.1.398",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]
