[tool.poetry]
name = "toptica-dlc-pro-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "toptica_dlc_pro"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

toptica-lasersdk = "^3.1.1"
util = {path = "../../../util", develop = true}
device-runtime = {path = "../../device/device.runtime", develop = true}

[tool.poetry.plugins."experiment_control.devices"]
"TopticaDLCPro" = "toptica_dlc_pro.runtime:TopticaDLCPro"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
mypy = "^1.7.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
