[tool.poetry]
name = "sequence-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "sequence"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

sqlalchemy = ">=2.0"
sqlalchemy-utils = "^0.40.0"
attrs = "^23.1.0"

sequence-configuration = {path = "../sequence.configuration", develop = true}
experiment-configuration = {path = "../../experiment/experiment.configuration", develop = true}
experiment-session = {path = "../../experiment/experiment.session", develop = true}
sql-model = {path = "../../sql_model", develop = true}
device-name = {path = "../../../devices/device/device.name", develop = true}
data-types = {path = "../../types/data_types", develop = true}
variable-name = {path = "../../variable/variable.name", develop = true}
parameter-types = {path = "../../types/parameter_types", develop = true}



[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
numpy = "^1.24.2"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
