[tool.poetry]
name = "waiting-widget"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "waiting_widget"}]

[tool.poetry.dependencies]
python = "^3.11"

pyqt6 = "^6.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
