[tool.poetry]
name = "experiment-control-compute-device-parameters"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "experiment_control"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

numpy = "^1.24.3"

device-config = {path = "../../devices/device/device.configuration", develop = true}
experiment-configuration = {path = "../../common/experiment/experiment.configuration", develop = true}
expression = {path = "../../common/expression", develop = true}
sequence-configuration = {path = "../../common/sequence/sequence.configuration", develop = true}
spincore-sequencer-runtime = {path = "../../devices/spincore_sequencer/spincore_sequencer.runtime", develop = true}
units = {path = "../../common/units", develop = true}
variable-name = {path = "../../common/variable/variable.name", develop = true}
variable-namespace = {path = "../../common/variable/variable.namespace", develop = true}
parameter-types = {path = "../../common/types/parameter_types", develop = true}
sequencer-channel = {path = "../../devices/sequencer/sequencer.channel", develop = true}
sequencer-instructions = {path = "../../devices/sequencer/sequencer.instructions", develop = true}
digital-lane-configuration = {path = "../../devices/sequencer/digital_lane/digital_lane.configuration", develop = true}
analog-lane-configuration = {path = "../../devices/sequencer/analog_lane/analog_lane.configuration", develop = true}
lane-configuration = {path = "../../common/lane/lane.configuration", develop = true}
camera-lane-configuration = {path = "../../devices/cameras/camera/camera_lane/camera_lane.configuration", develop = true}
atom-detector-configuration = {path = "../../devices/atom_detector/atom_detector.configuration", develop = true}
atom-detector-lane-configuration = {path = "../../devices/atom_detector/atom_detector_lane/atom_detector_lane.configuration", develop = true}


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
black = "^23.3.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
matplotlib = "^3.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
