[tool.poetry]
name = "ni6738-analog-card-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "ni6738_analog_card"}]

[tool.poetry.dependencies]
python = "^3.11"

pyqt6 = "^6.5.1"
ni6738-analog-card-configuration = {path = "../ni6738_analog_card.configuration", develop = true}
core-device = {path = "../../../core/core.device", develop = true}
core-types = {path = "../../../core/core.types", develop = true}
condetrol = {path = "../../../ui/condetrol", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
