[tool.poetry]
name = "ni6738-analog-card-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "ni6738_analog_card"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

pyqt6 = "^6.5.1"

device-configuration-editor = {path = "../../device/device.configuration_editor", develop = true}
device-server-name = {path = "../../remote_device/device_server/device_server.name", develop = true}
ni6738-analog-card-configuration = {path = "../ni6738_analog_card.configuration", develop = true}
sequencer-configuration-editor = {path = "../../sequencer/sequencer.configuration_editor", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
