[tool.poetry]
name = "spectum-awg-m4i66xx-x8-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spectum_awg_m4i66xx_x8"}]

[tool.poetry.dependencies]
python = "^3.10"

numpy = ">=1.18"
attrs = "^23.1.0"

util = {path = "../../../util", develop = true}
spectum-awg-m4i66xx-x8-configuration = {path = "../spectum_awg_m4i66xx-x8.configuration", develop = true}
device-runtime = {path = "../../device/device.runtime", develop = true}
settings-model = {path = "../../../common/settings_model"}




[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
