[tool.poetry]
name = "spectum-awg-m4i66xx-x8-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spectum_awg_m4i66xx_x8"}]

[tool.poetry.dependencies]
python = "^3.10"
device = {path = "../../device", develop = true}
pydantic = "^1.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
