[tool.poetry]
name = "trap-signal-generator-runtime"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "trap_signal_generator"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = "^1.10.4"
scipy = "^1.10.0"
trap-signal-generator-configuration = {path = "../trap_signal_generator.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
