[tool.poetry]
name = "digital-lane-model"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "digital_lane"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
lane-model = {path = "../../../../common/lane/lane.model", develop = true}
digital-lane-configuration = {path = "../digital_lane.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
