[tool.poetry]
name = "orca-quest"
version = "1.0.0"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

numpy = "^1.24.1"
attrs = "^23.1.0"
pyside6 = "^6.6.2"

caqtus-device = {path = "../../../caqtus/caqtus.device", develop = true}
caqtus-utils = {path = "../../../caqtus/caqtus.utils", develop = true}
caqtus-types = {path = "../../../caqtus/caqtus.types", develop = true}
caqtus-gui-condetrol = {path = "../../../caqtus/caqtus.gui/caqtus.gui.condetrol", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
