[tool.poetry]
name = "spincore-pulse-blaster-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spincore_pulse_blaster"}]

[tool.poetry.dependencies]
python = "^3.11"

attrs = "^23.1.0"

caqtus-utils = {path = "../../../../../caqtus.utils"}
caqtus-device = {path = "../../../../../caqtus.device"}


[tool.poetry.plugins."experiment_control.devices"]
"SpincorePulseBlaster" = "spincore_sequencer.runtime:SpincorePulseBlaster"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
