[tool.poetry]
name = "sequence"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
settings_model = { path = "../settings_model/", develop = true }
expression = { path = "../expression/", develop = true }
experiment_config = { path = "../experiment_config/", develop = true }
units = { path = "../units/", develop = true }
h5py = "^3.7.0"
numpy = "^1.23.4"
anytree = "^2.8.0"
watchdog = "^2.1.9"
pyqt6 = "^6.4.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
hypothesis = "^6.58.1"
black = "^22.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
