[tool.poetry]
name = "yaml-clipboard-mixin"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "yaml_clipboard_mixin"}]

[tool.poetry.dependencies]
python = "^3.10"
pyqt6 = "^6.5.3"
qabc = {path = "../qabc", develop = true}
settings-model = {path = "../../../common/settings_model", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
