[tool.poetry]
name = "ni6738-analog-card-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "ni6738_analog_card"}]

[tool.poetry.dependencies]
python = "^3.11"

nidaqmx = "^0.6.5"
numpy = "^1.24.1"
attrs = "^23.1.0"

log-exception = {path = "../../../common/log_exception", develop = true}
sequencer-instructions = {path = "../../sequencer/sequencer.instructions", develop = true}
sequencer-runtime = {path = "../../sequencer/sequencer.runtime", develop = true}
util = {path = "../../../util", develop = true}
duration-timer = {path = "../../../common/duration_timer", develop = true}



[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
