[tool.poetry]
name = "ni6738-analog-card-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "ni6738_analog_card"}]

[tool.poetry.dependencies]
python = "^3.11"

nidaqmx = "^0.6.5"
numpy = "^1.24.1"
attrs = "^23.1.0"

util = {path = "../../../util", develop = true}
core-device = {path = "../../../core/core.device", develop = true}

[tool.poetry.plugins."experiment_control.devices"]
"NI6738AnalogCard" = "ni6738_analog_card.runtime:NI6738AnalogCard"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
