[tool.poetry]
name = "camera-lane-model"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "camera_lane"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

lane-model = {path = "../../../../../common/lane/lane.model", develop = true}
camera-lane-configuration = {path = "../camera_lane.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
