[tool.poetry]
name = "shotviewer"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

pyqt6 = "^6.6.1"
platformdirs = "^4.1.0"
pyqtgraph = "^0.13.3"
core-session = {path = "../../core/core.session", develop = true}
sequence-hierarchy = {path = "../widgets/sequence_hierarchy", develop = true}
util = {path = "../../util", develop = true}
qabc = {path = "../widgets/qabc", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
mypy = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
