[tool.poetry]
name = "spincore-sequencer-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "spincore_sequencer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

device-configuration-editor = {path = "../../device/device.configuration_editor", develop = true}
sequencer-configuration-editor = {path = "../../sequencer/sequencer.configuration_editor", develop = true}
pyqt6 = "^6.5.1"
spincore-sequencer-configuration = {path = "../spincore_sequencer.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
