[tool.poetry]
name = "sequencer-channel"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "sequencer"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.0"
attrs = "^23.1.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
black = "^23.3.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
hypothesis = "^6.80.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
