[tool.poetry]
name = "variable-name"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "variable"}]

[tool.poetry.dependencies]
python = "^3.7"
settings-model = {path = "../../settings_model", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
