[tool.poetry]
name = "camera-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "camera"}]

[tool.poetry.dependencies]
python = "^3.10"
device = {path = "../../../device", develop = true}
pydantic = "^1.10.4"
camera-configuration = {path = "../camera.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
