[tool.poetry]
name = "spincore-sequencer-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spincore_sequencer"}]

[tool.poetry.dependencies]
python = "^3.10"

pydantic = "^1.10.4"

device-config = {path = "../../device/device.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
