[tool.poetry]
name = "spincore-sequencer-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spincore_sequencer"}]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.10.4"
device-config = {path = "../../../common/device_config", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
