[tool.poetry]
name = "imaging-source-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "imaging_source"}]

[tool.poetry.dependencies]
python = "^3.11"

numpy = "^1.24.2"
pydantic = "^1.10.5"

camera-runtime = {path = "../../camera/camera.runtime", develop = true}


[tool.poetry.group.dev.dependencies]
matplotlib = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
