[tool.poetry]
name = "imaging-source-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "imaging_source"}]

[tool.poetry.dependencies]
python = "^3.11"
camera-runtime = {path = "../../camera/camera.runtime", develop = true}
pydantic = "^1.10.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
