[tool.poetry]
name = "core-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

expression = {path = "../../common/expression", develop = true}
analog-lane-configuration = {path = "../../devices/sequencer/analog_lane/analog_lane.configuration", develop = true}
digital-lane-configuration = {path = "../../devices/sequencer/digital_lane/digital_lane.configuration", develop = true}
lane-configuration = {path = "../../common/lane/lane.configuration", develop = true}
variable-name = {path = "../../common/variable/variable.name", develop = true}
sequence-configuration = {path = "../../common/sequence/sequence.configuration", develop = true}
camera-lane-configuration = {path = "../../devices/cameras/camera/camera_lane/camera_lane.configuration", develop = true}
experiment-configuration = {path = "../../common/experiment/experiment.configuration", develop = true}
tweezer-arranger-lane-configuration = {path = "../../devices/tweezer_arranger/tweezer_arranger_lane/tweezer_arranger_lane.configuration", develop = true}
atom-detector-lane-configuration = {path = "../../devices/atom_detector/atom_detector_lane/atom_detector_lane.configuration", develop = true}
atom-detector-configuration = {path = "../../devices/atom_detector/atom_detector.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
