[tool.poetry]
name = "spincore-sequencer-runtime"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spincore_sequencer"}]

[tool.poetry.dependencies]
python = "^3.10"

pydantic = "^1.10.4"

device-runtime = {path = "../../device/device.runtime", develop = true}
log-exception = {path = "../../../common/log_exception", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
