[tool.poetry]
name = "tweezer-arranger-lane-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "tweezer_arranger_lane"}]

[tool.poetry.dependencies]
python = "^3.11"
lane-configuration = {path = "../../../../common/lane/lane.configuration", develop = true}
settings-model = {path = "../../../../common/settings_model", develop = true}
tweezer-arranger-configuration = {path = "../../tweezer_arranger.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
