[tool.poetry]
name = "aod-tweezer-arranger-runtime"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{ include = "aod_tweezer_arranger" }]

[tool.poetry.dependencies]
python = "^3.11, <3.12"

pycuda = "^2022.2.2"
numpy = "^1.25.1"
aod-tweezer-arranger-configuration = {path = "../aod_tweezer_arranger.configuration", develop = true}
tweezer-arranger-runtime = {path = "../tweezer_arranger.runtime", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.4.1"
matplotlib = "^3.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
