[tool.poetry]
name = "aod-tweezer-arranger-runtime"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{ include = "aod_tweezer_arranger" }]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

numpy = "^1.25.1"
cuda-python = "^12.2.0"
pypiwin32 = "^223"
attrs = "^23.1.0"

util = {path = "../../../util", develop = true}
aod-tweezer-arranger-configuration = {path = "../aod_tweezer_arranger.configuration", develop = true}
tweezer-arranger-runtime = {path = "../tweezer_arranger.runtime", develop = true}
spectum-awg-m4i66xx-x8-runtime = {path = "../../spectum_awg_m4i66xx-x8/spectum_awg_m4i66xx-x8.runtime", develop = true}



[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
mypy = "^1.4.1"
matplotlib = "^3.7.2"
scipy = "^1.11.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
