[tool.poetry]
name = "camera-lane-configuration"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "camera_lane"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
settings-model = {path = "../../../../../common/settings_model", develop = true}
pydantic = "^1.0"
lane-configuration = {path = "../../../../../common/lane/lane.configuration", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
