[tool.poetry]
name = "swabian-pulse-streamer"
version = "1.0.2"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

swabian-pulse-streamer-configuration = {path = "./swabian_pulse_streamer/swabian_pulse_streamer.configuration/", develop = true}
swabian-pulse-streamer-configuration-editor = {path = "./swabian_pulse_streamer/swabian_pulse_streamer.configuration_editor/", develop = true}
swabian-pulse-streamer-runtime = {path = "./swabian_pulse_streamer/swabian_pulse_streamer.runtime/", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
