[tool.poetry]
name = "swabian-pulse-streamer"
version = "0.1.0"
description = ""
authors = ["Dear <lechadoq@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"

pulsestreamer = "^1.7.0"

caqtus = {git = "https://github.com/damienBloch/caqtus.git", rev = "namespace_refactor"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
