[tool.poetry]
name = "device-configuration-editor"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique>"]
readme = "README.md"
packages = [{include = "device"}]

[tool.poetry.dependencies]
python = "^3.10"

pyqt6 = "^6.5.0"

device-config = {path = "../device.configuration", develop = true}
device-server-name = {path = "../../remote_device/device_server/device_server.name", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
