[tool.poetry]
name = "spincore-pulse-blaster-configuration"
version = "1.0.0"
description = ""
authors = ["Damien Bloch <bloc.dam@gmail.com>"]
readme = "README.md"
packages = [{include = "spincore_pulse_blaster"}]

[tool.poetry.dependencies]
python = "^3.11"

caqtus-device = {path = "../../../../../caqtus.device"}
caqtus-utils = {path = "../../../../../caqtus.utils"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
