[tool.poetry]
name = "swabian-pulse-streamer-configuration-editor"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "swabian_pulse_streamer"}]

[tool.poetry.dependencies]
python = "^3.11"

pyqt6 = "^6.5.2"
condetrol = {path = "../../../ui/condetrol", develop = true}
core-device = {path = "../../../core/core.device", develop = true}
core-types = {path = "../../../core/core.types", develop = true}
swabian-pulse-streamer-configuration = {path = "../swabian_pulse_streamer.configuration", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
