[tool.poetry]
name = "swabian-pulse-streamer-configuration-editor"
version = "0.1.0"
description = ""
authors = ["damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "swabian_pulse_streamer"}]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
device-configuration-editor = {path = "../../device/device.configuration_editor", develop = true}
sequencer-configuration-editor = {path = "../../sequencer/sequencer.configuration_editor", develop = true}
swabian-pulse-streamer-configuration = {path = "../swabian_pulse_streamer.configuration", develop = true}
pyqt6 = "^6.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
