[tool.poetry]
name = "condetrol"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique.fr>"]

[tool.poetry.dependencies]
python = "^3.11"

pyqt6 = "^6.6.1"
pyqtgraph = "^0.13.3"
pydantic = "^2.5.3"

core-session = {path = "../../core/core.session", develop = true}
core-device = {path = "../../core/core.device", develop = true}

qabc = {path = "../widgets/qabc", develop = true}
pyqt6-charts = "^6.6.0"
sequence-hierarchy = {path = "../widgets/sequence_hierarchy", develop = true}
core-experiment = {path = "../../core/core.experiment", develop = true}
waiting-widget = {path = "../widgets/waiting_widget", develop = true}
exception-tree = {path = "../widgets/exception_tree", develop = true}


[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
