[tool.poetry]
name = "condetrol"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique.fr>"]

[tool.poetry.dependencies]
python = "^3.12"

pyqt6 = "^6.6.1"

core-session = {path = "../../core/core.session", develop = true}
core-device = {path = "../../core/core.device", develop = true}

qabc = {path = "../widgets/qabc", develop = true}


[tool.poetry.group.dev.dependencies]


[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
