[tool.poetry]
name = "condetrol"
version = "0.1.0"
description = ""
authors = ["Damien Bloch <damien.bloch@institutoptique.fr>"]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

pydantic = "^2.5.3"
pyside6 = "^6.6.1"
qdarkstyle = "^3.2.3"
qtawesome = "^1.3.0"
matplotlib = "^3.8.2"

core-session = {path = "../../core/core.session", develop = true}
core-device = {path = "../../core/core.device", develop = true}
core-types = {path = "../../core/core.types", develop = true}

qabc = {path = "../widgets/qabc", develop = true}
sequence-hierarchy = {path = "../widgets/sequence_hierarchy", develop = true}
core-experiment = {path = "../../core/core.experiment", develop = true}
waiting-widget = {path = "../widgets/waiting_widget", develop = true}
exception-tree = {path = "../widgets/exception_tree", develop = true}


[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"


[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
