[tool.poetry]
name = "graphplot"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11, <3.13"
sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}
util = {path = "../../util", develop = true}
pandas = "^2.1.3"
analyza-loading-importers = {path = "../../analyza/analyza.loading/analyza.loading.importers", develop = true}
experiment-session = {path = "../../common/experiment/experiment.session", develop = true}
matplotlib = "^3.8.2"
seaborn = "^0.13.0"
numpy = "^1.26.2"
pyqt6 = "^6.6.0"
sequence-hierarchy = {path = "../widgets/sequence_hierarchy", develop = true}
qabc = {path = "../widgets/qabc", develop = true}


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
mypy = "^1.7.0"
pandas-stubs = "^2.1.1.230928"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
