[tool.poetry]
name = "core-session"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"
experiment-session = {path = "../../common/experiment/experiment.session", develop = true}
sequence-runtime = {path = "../../common/sequence/sequence.runtime", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
