[tool.poetry]
name = "core-session"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

sqlalchemy = "^2.0.23"
sqlalchemy-utils = "^0.41.1"
psycopg2 = "^2.9.9"
platformdirs = "^4.1.0"

util = {path = "../../util", develop = true}
core-types = {path = "../core.types", develop = true}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
