[tool.poetry]
name = "core-session"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11, <3.13"

sqlalchemy = "^2.0.23"
sqlalchemy-utils = "^0.41.1"
psycopg2 = "^2.9.9"
platformdirs = "^4.1.0"
returns = "^0.22.0"

util = {path = "../../util", develop = true}
core-types = {path = "../core.types", develop = true}
experiment-configuration = {path = "../../common/experiment/experiment.configuration", develop = true}
sequence-configuration = {path = "../../common/sequence/sequence.configuration", develop = true}
variable-name = {path = "../../common/variable/variable.name", develop = true}

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.1"
jupyter = "^1.0.0"
black = "^23.11.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["returns.contrib.mypy.returns_plugin"]
