[tool.poetry]
name = "core-session"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{include = "core"}]

[tool.poetry.dependencies]
python = "^3.11"

sqlalchemy = "^2.0.23"
sqlalchemy-utils = "^0.41.1"
platformdirs = "^4.1.0"
returns = "^0.22.0"

util = {path = "../../util", develop = true}
core-types = {path = "../core.types", develop = true}
core-device = {path = "../core.device", develop = true}

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
black = "^23.11.0"
mypy = "^1.8.0"
pyright = "^1.1.344"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
hypothesis = "^6.92.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["returns.contrib.mypy.returns_plugin"]
