[tool.poetry]
name = "aod-tweezer-arranger-configuration"
version = "0.1.0"
description = ""
authors = ["Damien <damien.bloch@institutoptique.fr>"]
readme = "README.md"
packages = [{ include = "aod_tweezer_arranger" }]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
settings-model = { path = "../../../common/settings_model", develop = true }
tweezer-arranger-configuration = { path = "../tweezer_arranger.configuration", develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
