name: Push
run-name: ${{ github.actor }} triggered ${{ github.event_name }} on ${{ github.ref }}
on:
  pull_request:
    branches: [ "main" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - id: changed-files
        uses: tj-actions/changed-files@v36
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }} # Only run on changed files
      - id: changed-python-files
        uses: tj-actions/changed-files@v36
        with:
          files: "**.py"
          files_ignore: "**/*_ui.py"
      - name: Run linter
        if: steps.changed-python-files.outputs.any_changed == 'true'
        env:
          CHANGED_PYTHON_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
        run: uv run ruff check $CHANGED_PYTHON_FILES
      - name: Run check types
        if: steps.changed-python-files.outputs.any_changed == 'true'
        env:
          CHANGED_PYTHON_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
        run: uv run pyright $CHANGED_PYTHON_FILES
