name: Push
run-name: ${{ github.actor }} triggered ${{ github.event_name }} on ${{ github.ref }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
#          cache: 'pip'
      - name: Install Hatch
        uses: pypa/hatch@install
      - id: changed-files
        uses: tj-actions/changed-files@v36
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }} # Only run on changed files
