name: Push
run-name: ${{ github.actor }} triggered ${{ github.event_name }} on ${{ github.ref }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Hatch
        run: pipx install hatch
      - uses: pre-commit/action@v3.0.1